// WAKE Protocol challenge bank
// Math: 400 easy mental-arithmetic challenges
// Typing: 400 original morning/reflection challenges

export const mathChallenges = [
    { question: '7 + 5', answer: 12 },
    { question: '14 + 6', answer: 20 },
    { question: '8 + 9', answer: 17 },
    { question: '12 + 8', answer: 20 },
    { question: '11 + 7', answer: 18 },
    { question: '15 + 9', answer: 24 },
    { question: '13 + 8', answer: 21 },
    { question: '16 + 7', answer: 23 },
    { question: '18 + 6', answer: 24 },
    { question: '17 + 9', answer: 26 },
    { question: '19 + 7', answer: 26 },
    { question: '21 + 8', answer: 29 },
    { question: '22 + 9', answer: 31 },
    { question: '14 + 13', answer: 27 },
    { question: '16 + 12', answer: 28 },
    { question: '18 + 9', answer: 27 },
    { question: '23 + 7', answer: 30 },
    { question: '24 + 8', answer: 32 },
    { question: '25 + 6', answer: 31 },
    { question: '27 + 5', answer: 32 },
    { question: '15 + 16', answer: 31 },
    { question: '17 + 14', answer: 31 },
    { question: '19 + 12', answer: 31 },
    { question: '21 + 13', answer: 34 },
    { question: '22 + 11', answer: 33 },
    { question: '24 + 14', answer: 38 },
    { question: '26 + 13', answer: 39 },
    { question: '28 + 11', answer: 39 },
    { question: '29 + 10', answer: 39 },
    { question: '31 + 8', answer: 39 },
    { question: '12 + 17', answer: 29 },
    { question: '13 + 16', answer: 29 },
    { question: '14 + 18', answer: 32 },
    { question: '15 + 19', answer: 34 },
    { question: '16 + 17', answer: 33 },
    { question: '18 + 15', answer: 33 },
    { question: '20 + 13', answer: 33 },
    { question: '21 + 16', answer: 37 },
    { question: '23 + 12', answer: 35 },
    { question: '25 + 14', answer: 39 },
    { question: '27 + 12', answer: 39 },
    { question: '28 + 13', answer: 41 },
    { question: '29 + 14', answer: 43 },
    { question: '31 + 12', answer: 43 },
    { question: '32 + 15', answer: 47 },
    { question: '34 + 11', answer: 45 },
    { question: '35 + 13', answer: 48 },
    { question: '36 + 12', answer: 48 },
    { question: '38 + 11', answer: 49 },
    { question: '39 + 10', answer: 49 },
    { question: '14 - 6', answer: 8 },
    { question: '20 - 7', answer: 13 },
    { question: '17 - 9', answer: 8 },
    { question: '25 - 8', answer: 17 },
    { question: '18 - 5', answer: 13 },
    { question: '23 - 7', answer: 16 },
    { question: '30 - 12', answer: 18 },
    { question: '27 - 9', answer: 18 },
    { question: '32 - 14', answer: 18 },
    { question: '29 - 11', answer: 18 },
    { question: '35 - 16', answer: 19 },
    { question: '31 - 13', answer: 18 },
    { question: '40 - 17', answer: 23 },
    { question: '34 - 15', answer: 19 },
    { question: '38 - 19', answer: 19 },
    { question: '42 - 18', answer: 24 },
    { question: '45 - 17', answer: 28 },
    { question: '37 - 14', answer: 23 },
    { question: '41 - 16', answer: 25 },
    { question: '50 - 23', answer: 27 },
    { question: '44 - 19', answer: 25 },
    { question: '48 - 21', answer: 27 },
    { question: '52 - 27', answer: 25 },
    { question: '46 - 18', answer: 28 },
    { question: '55 - 24', answer: 31 },
    { question: '57 - 29', answer: 28 },
    { question: '60 - 26', answer: 34 },
    { question: '53 - 17', answer: 36 },
    { question: '49 - 22', answer: 27 },
    { question: '58 - 31', answer: 27 },
    { question: '63 - 28', answer: 35 },
    { question: '67 - 29', answer: 38 },
    { question: '70 - 34', answer: 36 },
    { question: '62 - 17', answer: 45 },
    { question: '68 - 24', answer: 44 },
    { question: '72 - 35', answer: 37 },
    { question: '75 - 28', answer: 47 },
    { question: '64 - 19', answer: 45 },
    { question: '69 - 27', answer: 42 },
    { question: '80 - 35', answer: 45 },
    { question: '73 - 18', answer: 55 },
    { question: '77 - 29', answer: 48 },
    { question: '85 - 37', answer: 48 },
    { question: '90 - 42', answer: 48 },
    { question: '88 - 31', answer: 57 },
    { question: '95 - 46', answer: 49 },
    { question: '100 - 37', answer: 63 },
    { question: '84 - 29', answer: 55 },
    { question: '91 - 38', answer: 53 },
    { question: '79 - 24', answer: 55 },
    { question: '2 × 6', answer: 12 },
    { question: '3 × 4', answer: 12 },
    { question: '3 × 5', answer: 15 },
    { question: '4 × 4', answer: 16 },
    { question: '4 × 5', answer: 20 },
    { question: '5 × 5', answer: 25 },
    { question: '6 × 4', answer: 24 },
    { question: '7 × 3', answer: 21 },
    { question: '8 × 3', answer: 24 },
    { question: '9 × 3', answer: 27 },
    { question: '4 × 6', answer: 24 },
    { question: '5 × 6', answer: 30 },
    { question: '6 × 6', answer: 36 },
    { question: '7 × 4', answer: 28 },
    { question: '8 × 4', answer: 32 },
    { question: '9 × 4', answer: 36 },
    { question: '5 × 7', answer: 35 },
    { question: '6 × 7', answer: 42 },
    { question: '7 × 5', answer: 35 },
    { question: '8 × 5', answer: 40 },
    { question: '9 × 5', answer: 45 },
    { question: '6 × 8', answer: 48 },
    { question: '7 × 6', answer: 42 },
    { question: '8 × 6', answer: 48 },
    { question: '9 × 6', answer: 54 },
    { question: '7 × 7', answer: 49 },
    { question: '8 × 7', answer: 56 },
    { question: '9 × 7', answer: 63 },
    { question: '6 × 9', answer: 54 },
    { question: '7 × 8', answer: 56 },
    { question: '8 × 8', answer: 64 },
    { question: '9 × 8', answer: 72 },
    { question: '7 × 9', answer: 63 },
    { question: '8 × 9', answer: 72 },
    { question: '9 × 9', answer: 81 },
    { question: '11 × 3', answer: 33 },
    { question: '12 × 3', answer: 36 },
    { question: '10 × 4', answer: 40 },
    { question: '11 × 4', answer: 44 },
    { question: '12 × 4', answer: 48 },
    { question: '10 × 5', answer: 50 },
    { question: '11 × 5', answer: 55 },
    { question: '12 × 5', answer: 60 },
    { question: '10 × 6', answer: 60 },
    { question: '11 × 6', answer: 66 },
    { question: '12 × 6', answer: 72 },
    { question: '10 × 7', answer: 70 },
    { question: '11 × 7', answer: 77 },
    { question: '12 × 7', answer: 84 },
    { question: '10 × 8', answer: 80 },
    { question: '12 ÷ 2', answer: 6 },
    { question: '15 ÷ 3', answer: 5 },
    { question: '16 ÷ 4', answer: 4 },
    { question: '18 ÷ 3', answer: 6 },
    { question: '20 ÷ 4', answer: 5 },
    { question: '21 ÷ 3', answer: 7 },
    { question: '24 ÷ 4', answer: 6 },
    { question: '25 ÷ 5', answer: 5 },
    { question: '27 ÷ 3', answer: 9 },
    { question: '28 ÷ 4', answer: 7 },
    { question: '30 ÷ 5', answer: 6 },
    { question: '32 ÷ 4', answer: 8 },
    { question: '35 ÷ 5', answer: 7 },
    { question: '36 ÷ 6', answer: 6 },
    { question: '40 ÷ 5', answer: 8 },
    { question: '42 ÷ 6', answer: 7 },
    { question: '45 ÷ 5', answer: 9 },
    { question: '48 ÷ 6', answer: 8 },
    { question: '49 ÷ 7', answer: 7 },
    { question: '50 ÷ 5', answer: 10 },
    { question: '54 ÷ 6', answer: 9 },
    { question: '56 ÷ 7', answer: 8 },
    { question: '60 ÷ 6', answer: 10 },
    { question: '63 ÷ 7', answer: 9 },
    { question: '64 ÷ 8', answer: 8 },
    { question: '72 ÷ 8', answer: 9 },
    { question: '81 ÷ 9', answer: 9 },
    { question: '90 ÷ 9', answer: 10 },
    { question: '96 ÷ 8', answer: 12 },
    { question: '100 ÷ 10', answer: 10 },
    { question: '66 ÷ 6', answer: 11 },
    { question: '70 ÷ 7', answer: 10 },
    { question: '77 ÷ 7', answer: 11 },
    { question: '80 ÷ 8', answer: 10 },
    { question: '84 ÷ 7', answer: 12 },
    { question: '88 ÷ 8', answer: 11 },
    { question: '90 ÷ 10', answer: 9 },
    { question: '99 ÷ 9', answer: 11 },
    { question: '108 ÷ 9', answer: 12 },
    { question: '120 ÷ 10', answer: 12 },
    { question: '132 ÷ 11', answer: 12 },
    { question: '144 ÷ 12', answer: 12 },
    { question: '121 ÷ 11', answer: 11 },
    { question: '132 ÷ 12', answer: 11 },
    { question: '150 ÷ 10', answer: 15 },
    { question: '160 ÷ 10', answer: 16 },
    { question: '180 ÷ 12', answer: 15 },
    { question: '200 ÷ 10', answer: 20 },
    { question: '210 ÷ 10', answer: 21 },
    { question: '240 ÷ 12', answer: 20 },
    { question: '6 + 13', answer: 19 },
    { question: '9 + 14', answer: 23 },
    { question: '12 + 15', answer: 27 },
    { question: '17 + 11', answer: 28 },
    { question: '18 + 13', answer: 31 },
    { question: '22 + 14', answer: 36 },
    { question: '26 + 15', answer: 41 },
    { question: '27 + 16', answer: 43 },
    { question: '30 + 14', answer: 44 },
    { question: '33 + 15', answer: 48 },
    { question: '35 + 16', answer: 51 },
    { question: '37 + 14', answer: 51 },
    { question: '39 + 15', answer: 54 },
    { question: '41 + 17', answer: 58 },
    { question: '43 + 16', answer: 59 },
    { question: '45 + 18', answer: 63 },
    { question: '47 + 12', answer: 59 },
    { question: '48 + 15', answer: 63 },
    { question: '51 + 18', answer: 69 },
    { question: '53 + 16', answer: 69 },
    { question: '55 + 17', answer: 72 },
    { question: '57 + 14', answer: 71 },
    { question: '59 + 18', answer: 77 },
    { question: '61 + 16', answer: 77 },
    { question: '63 + 17', answer: 80 },
    { question: '65 + 18', answer: 83 },
    { question: '67 + 15', answer: 82 },
    { question: '69 + 17', answer: 86 },
    { question: '71 + 16', answer: 87 },
    { question: '73 + 18', answer: 91 },
    { question: '75 + 17', answer: 92 },
    { question: '77 + 16', answer: 93 },
    { question: '79 + 18', answer: 97 },
    { question: '81 + 17', answer: 98 },
    { question: '83 + 16', answer: 99 },
    { question: '85 + 18', answer: 103 },
    { question: '87 + 17', answer: 104 },
    { question: '89 + 16', answer: 105 },
    { question: '91 + 18', answer: 109 },
    { question: '93 + 17', answer: 110 },
    { question: '95 + 16', answer: 111 },
    { question: '97 + 18', answer: 115 },
    { question: '99 + 17', answer: 116 },
    { question: '102 + 16', answer: 118 },
    { question: '104 + 17', answer: 121 },
    { question: '106 + 18', answer: 124 },
    { question: '108 + 16', answer: 124 },
    { question: '110 + 17', answer: 127 },
    { question: '112 + 18', answer: 130 },
    { question: '114 + 16', answer: 130 },
    { question: '116 + 17', answer: 133 },
    { question: '118 + 18', answer: 136 },
    { question: '120 + 16', answer: 136 },
    { question: '122 + 17', answer: 139 },
    { question: '124 + 18', answer: 142 },
    { question: '126 + 16', answer: 142 },
    { question: '128 + 17', answer: 145 },
    { question: '130 + 18', answer: 148 },
    { question: '132 + 16', answer: 148 },
    { question: '134 + 17', answer: 151 },
    { question: '136 + 18', answer: 154 },
    { question: '138 + 16', answer: 154 },
    { question: '140 + 17', answer: 157 },
    { question: '142 + 18', answer: 160 },
    { question: '144 + 16', answer: 160 },
    { question: '146 + 17', answer: 163 },
    { question: '148 + 18', answer: 166 },
    { question: '150 + 16', answer: 166 },
    { question: '152 + 17', answer: 169 },
    { question: '154 + 18', answer: 172 },
    { question: '156 + 16', answer: 172 },
    { question: '158 + 17', answer: 175 },
    { question: '160 + 18', answer: 178 },
    { question: '162 + 16', answer: 178 },
    { question: '164 + 17', answer: 181 },
    { question: '166 + 18', answer: 184 },
    { question: '168 + 16', answer: 184 },
    { question: '170 + 17', answer: 187 },
    { question: '172 + 18', answer: 190 },
    { question: '174 + 16', answer: 190 },
    { question: '176 + 17', answer: 193 },
    { question: '178 + 18', answer: 196 },
    { question: '180 + 16', answer: 196 },
    { question: '182 + 17', answer: 199 },
    { question: '184 + 18', answer: 202 },
    { question: '186 + 16', answer: 202 },
    { question: '188 + 17', answer: 205 },
    { question: '190 + 18', answer: 208 },
    { question: '63 + 15', answer: 78 },
    { question: '65 + 17', answer: 82 },
    { question: '67 + 14', answer: 81 },
    { question: '69 + 16', answer: 85 },
    { question: '71 + 18', answer: 89 },
    { question: '73 + 15', answer: 88 },
    { question: '75 + 14', answer: 89 },
    { question: '77 + 16', answer: 93 },
    { question: '79 + 17', answer: 96 },
    { question: '81 + 15', answer: 96 },
    { question: '83 + 16', answer: 99 },
    { question: '85 + 14', answer: 99 },
    { question: '87 + 17', answer: 104 },
    { question: '89 + 15', answer: 104 },
    { question: '91 + 16', answer: 107 },
    { question: '93 + 14', answer: 107 },
    { question: '21 - 6', answer: 15 },
    { question: '24 - 9', answer: 15 },
    { question: '28 - 13', answer: 15 },
    { question: '33 - 15', answer: 18 },
    { question: '36 - 17', answer: 19 },
    { question: '39 - 12', answer: 27 },
    { question: '43 - 18', answer: 25 },
    { question: '47 - 19', answer: 28 },
    { question: '51 - 16', answer: 35 },
    { question: '54 - 21', answer: 33 },
    { question: '56 - 18', answer: 38 },
    { question: '59 - 24', answer: 35 },
    { question: '61 - 17', answer: 44 },
    { question: '65 - 23', answer: 42 },
    { question: '68 - 19', answer: 49 },
    { question: '71 - 26', answer: 45 },
    { question: '74 - 18', answer: 56 },
    { question: '76 - 27', answer: 49 },
    { question: '78 - 19', answer: 59 },
    { question: '82 - 24', answer: 58 },
    { question: '84 - 17', answer: 67 },
    { question: '86 - 28', answer: 58 },
    { question: '89 - 21', answer: 68 },
    { question: '92 - 34', answer: 58 },
    { question: '94 - 27', answer: 67 },
    { question: '96 - 18', answer: 78 },
    { question: '98 - 29', answer: 69 },
    { question: '99 - 36', answer: 63 },
    { question: '105 - 28', answer: 77 },
    { question: '110 - 35', answer: 75 },
    { question: '112 - 27', answer: 85 },
    { question: '115 - 39', answer: 76 },
    { question: '118 - 42', answer: 76 },
    { question: '120 - 44', answer: 76 },
    { question: '125 - 38', answer: 87 },
    { question: '130 - 45', answer: 85 },
    { question: '135 - 47', answer: 88 },
    { question: '140 - 52', answer: 88 },
    { question: '145 - 56', answer: 89 },
    { question: '150 - 63', answer: 87 },
    { question: '2 × 7', answer: 14 },
    { question: '2 × 8', answer: 16 },
    { question: '2 × 9', answer: 18 },
    { question: '3 × 6', answer: 18 },
    { question: '3 × 7', answer: 21 },
    { question: '3 × 8', answer: 24 },
    { question: '3 × 9', answer: 27 },
    { question: '4 × 7', answer: 28 },
    { question: '4 × 8', answer: 32 },
    { question: '4 × 9', answer: 36 },
    { question: '5 × 8', answer: 40 },
    { question: '5 × 9', answer: 45 },
    { question: '6 × 10', answer: 60 },
    { question: '7 × 10', answer: 70 },
    { question: '8 × 10', answer: 80 },
    { question: '9 × 10', answer: 90 },
    { question: '10 × 2', answer: 20 },
    { question: '10 × 3', answer: 30 },
    { question: '10 × 7', answer: 70 },
    { question: '10 × 9', answer: 90 },
    { question: '11 × 2', answer: 22 },
    { question: '11 × 6', answer: 66 },
    { question: '11 × 8', answer: 88 },
    { question: '12 × 2', answer: 24 },
    { question: '12 × 8', answer: 96 },
    { question: '12 × 9', answer: 108 },
    { question: '13 × 2', answer: 26 },
    { question: '13 × 3', answer: 39 },
    { question: '14 × 2', answer: 28 },
    { question: '14 × 3', answer: 42 },
    { question: '15 × 2', answer: 30 },
    { question: '15 × 3', answer: 45 },
    { question: '16 × 2', answer: 32 },
    { question: '16 × 3', answer: 48 },
    { question: '17 × 2', answer: 34 },
    { question: '17 × 3', answer: 51 },
    { question: '18 × 2', answer: 36 },
    { question: '18 × 3', answer: 54 },
    { question: '19 × 2', answer: 38 },
    { question: '19 × 3', answer: 57 },
    { question: '14 ÷ 2', answer: 7 },
    { question: '18 ÷ 2', answer: 9 },
    { question: '20 ÷ 2', answer: 10 },
    { question: '22 ÷ 2', answer: 11 },
    { question: '24 ÷ 2', answer: 12 },
    { question: '26 ÷ 2', answer: 13 },
    { question: '28 ÷ 2', answer: 14 },
    { question: '30 ÷ 2', answer: 15 },
    { question: '32 ÷ 2', answer: 16 },
    { question: '34 ÷ 2', answer: 17 },
    { question: '36 ÷ 2', answer: 18 },
    { question: '38 ÷ 2', answer: 19 },
    { question: '40 ÷ 2', answer: 20 },
    { question: '42 ÷ 2', answer: 21 },
    { question: '44 ÷ 2', answer: 22 },
    { question: '46 ÷ 2', answer: 23 },
    { question: '48 ÷ 2', answer: 24 },
    { question: '50 ÷ 2', answer: 25 },
    { question: '52 ÷ 2', answer: 26 },
    { question: '54 ÷ 2', answer: 27 },
    { question: '56 ÷ 2', answer: 28 },
    { question: '58 ÷ 2', answer: 29 },
    { question: '60 ÷ 2', answer: 30 },
    { question: '62 ÷ 2', answer: 31 },
    { question: '64 ÷ 2', answer: 32 },
    { question: '66 ÷ 2', answer: 33 },
    { question: '68 ÷ 2', answer: 34 },
    { question: '70 ÷ 2', answer: 35 },
    { question: '72 ÷ 2', answer: 36 },
    { question: '74 ÷ 2', answer: 37 },
    { question: '76 ÷ 2', answer: 38 },
    { question: '78 ÷ 2', answer: 39 },
    { question: '80 ÷ 2', answer: 40 },
    { question: '82 ÷ 2', answer: 41 },
    { question: '84 ÷ 2', answer: 42 },
    { question: '86 ÷ 2', answer: 43 },
    { question: '88 ÷ 2', answer: 44 },
    { question: '90 ÷ 2', answer: 45 },
    { question: '92 ÷ 2', answer: 46 },
    { question: '94 ÷ 2', answer: 47 },
    { question: '4 + 17', answer: 21 },
    { question: '8 + 16', answer: 24 },
    { question: '11 + 19', answer: 30 },
    { question: '14 + 21', answer: 35 },
    { question: '16 + 22', answer: 38 },
    { question: '19 + 24', answer: 43 },
    { question: '22 + 25', answer: 47 },
    { question: '25 + 27', answer: 52 },
    { question: '28 + 26', answer: 54 },
    { question: '31 + 29', answer: 60 },
    { question: '34 + 27', answer: 61 },
    { question: '36 + 28', answer: 64 },
    { question: '38 + 25', answer: 63 },
    { question: '42 + 26', answer: 68 },
    { question: '44 + 27', answer: 71 },
    { question: '46 + 29', answer: 75 },
    { question: '49 + 28', answer: 77 },
    { question: '52 + 27', answer: 79 },
    { question: '54 + 29', answer: 83 },
    { question: '56 + 31', answer: 87 },
    { question: '96 - 48', answer: 48 },
    { question: '84 ÷ 7', answer: 12 },
    { question: '13 × 4', answer: 52 },
    { question: '18 + 24', answer: 42 },
    { question: '75 - 25', answer: 50 },
    { question: '11 × 5', answer: 55 },
    { question: '96 ÷ 12', answer: 8 },
    { question: '27 + 36', answer: 63 },
    { question: '82 - 37', answer: 45 },
    { question: '14 × 3', answer: 42 },
    { question: '108 ÷ 12', answer: 9 },
    { question: '29 + 34', answer: 63 },
    { question: '90 - 45', answer: 45 },
    { question: '12 × 7', answer: 84 },
    { question: '144 ÷ 12', answer: 12 },
    { question: '38 + 27', answer: 65 },
    { question: '76 - 28', answer: 48 },
    { question: '15 × 4', answer: 60 },
    { question: '120 ÷ 10', answer: 12 },
    { question: '47 + 26', answer: 73 },
  ]
  
  export const typingChallenges = [
    'Wake up and remember that today is still unwritten.',
    'You are here, and that is already worth being grateful for.',
    'Begin today with intention, not with yesterday\'s regrets.',
    'You cannot change yesterday, but you can shape today.',
    'The way you begin the morning can shape the way you meet the day.',
    'Before chasing the world, remember to check in with yourself.',
    'Do not measure your life only by what you have achieved.',
    'A quiet morning can remind you what truly matters.',
    'You do not need a perfect day to have a meaningful one.',
    'Start with gratitude for what is already in your hands.',
    'Be present enough to notice the life you are living.',
    'Do not rush past today while waiting for tomorrow.',
    'Your attention is one of the most valuable things you own.',
    'Choose what deserves your energy before the world chooses for you.',
    'Not every problem deserves your peace.',
    'You cannot control every event, but you can choose your response.',
    'Protect your peace without losing your kindness.',
    'Strength is often quiet, patient, and consistent.',
    'You can be strong without becoming hard.',
    'Let patience be part of your strength.',
    'A difficult day does not mean a difficult life.',
    'You have survived days you once thought you could not.',
    'Keep going, but remember why you started.',
    'Progress is still progress when nobody else sees it.',
    'Small actions repeated with purpose can change a life.',
    'Consistency can carry you where motivation cannot.',
    'Do the next right thing, even when the whole path is unclear.',
    'You do not need to see the entire staircase to take the next step.',
    'Start before you feel completely ready.',
    'Courage often begins with one uncomfortable step.',
    'Do not let fear make decisions that belong to you.',
    'Failure can teach you without defining you.',
    'A mistake is an event, not an identity.',
    'Learn from yesterday without living inside it.',
    'You can begin again without pretending you never struggled.',
    'There is no shame in starting over with more wisdom.',
    'Growth often feels uncomfortable before it feels rewarding.',
    'Be willing to outgrow the version of yourself that once felt safe.',
    'Your future is built from ordinary choices made repeatedly.',
    'The person you become is shaped by what you practice.',
    'Discipline is choosing what matters over what feels easiest.',
    'Do not confuse comfort with progress.',
    'Do not confuse busyness with purpose.',
    'Make room for what matters instead of filling every space.',
    'A full schedule does not guarantee a full life.',
    'Work hard, but remember that your worth is larger than your productivity.',
    'Rest is not failure; sometimes rest is preparation.',
    'You are allowed to move at a pace that you can sustain.',
    'Do not compare your chapter to someone else\'s entire story.',
    'Be honest with yourself before asking the world to understand you.',
    'Self-awareness is the beginning of meaningful change.',
    'Ask yourself what you are avoiding and why.',
    'Sometimes the answer you need begins with an honest question.',
    'Listen to yourself without immediately judging what you hear.',
    'You can acknowledge your weaknesses without becoming ashamed of them.',
    'Knowing what you need is a form of strength.',
    'Your feelings deserve attention, but they do not have to control every action.',
    'You can feel afraid and still act with courage.',
    'You can be uncertain and still move forward.',
    'You can be tired and still be worthy of compassion.',
    'You do not have to have everything figured out today.',
    'Clarity often arrives after you begin moving.',
    'Give yourself permission to learn as you go.',
    'Your path does not need to look like anyone else\'s.',
    'There is value in becoming someone only you could become.',
    'Do not abandon yourself to meet someone else\'s expectations.',
    'Your life is not a race against another person\'s timeline.',
    'Make choices that your future self can respect.',
    'Become someone you would be proud to meet.',
    'Kindness is not weakness; it is strength under control.',
    'Be kind even when kindness is not rewarded.',
    'Do good because it is good, not because someone is watching.',
    'Do not let another person\'s cruelty decide who you become.',
    'You can answer anger without becoming angry.',
    'Respond with character when someone gives you a reason not to.',
    'Forgiveness does not require forgetting the lesson.',
    'You can set boundaries without becoming bitter.',
    'Treat people with dignity, even when you disagree.',
    'A small act of kindness can change the direction of someone\'s day.',
    'You never know what someone else is carrying.',
    'Speak to people in a way you would want to be remembered.',
    'Leave people with more hope than you found them with.',
    'Listen to understand before preparing to respond.',
    'Respect is shown most clearly when there is nothing to gain.',
    'Your character appears in how you treat people who cannot help you.',
    'Choose compassion when judgment would be easier.',
    'Do not repay harm with more harm.',
    'Be the person who breaks the cycle.',
    'A gentle response can be a powerful one.',
    'Gratitude changes what you notice.',
    'Notice the ordinary things that make your life possible.',
    'Be grateful for another morning, even if the morning is difficult.',
    'Do not overlook what once felt like a dream.',
    'Appreciate people while they are still part of your everyday life.',
    'Some of life\'s greatest gifts arrive without announcing themselves.',
    'Slow down enough to notice what you usually take for granted.',
    'The ordinary can become precious when you learn to pay attention.',
    'You do not need more possessions to practice gratitude.',
    'A grateful mind sees abundance where an impatient mind sees lack.',
    'Remember how much you once wished for what you have today.',
    'Give thanks for the lessons as well as the victories.',
    'There is wisdom in appreciating what cannot be bought.',
    'Do not let wanting more make you blind to enough.',
    'A meaningful life is not measured only by what can be counted.',
    'Peace often grows when comparison becomes quieter.',
    'Be thankful for people who make life lighter.',
    'Remember that time with loved ones is never ordinary.',
    'Some moments become precious only after they are gone.',
    'Pay attention while you are still living the moments you will remember.',
    'Your goals matter, but so does the person you become while pursuing them.',
    'Do not sacrifice your entire life for a future you never stop postponing.',
    'Ambition is useful when it serves a life you actually want.',
    'Success without peace can become another kind of failure.',
    'Build a life you do not constantly need to escape from.',
    'Let your goals challenge you without consuming you.',
    'Work toward something meaningful, not merely something impressive.',
    'Choose progress that you can sustain for years.',
    'Your worth does not rise and fall with your achievements.',
    'Do not let applause become the reason you keep going.',
    'Build for meaning, not only for recognition.',
    'The goal is not to look successful; it is to live meaningfully.',
    'Measure progress by who you are becoming, not only what you possess.',
    'A meaningful achievement is one that does not require you to lose yourself.',
    'Let your ambition have a conscience.',
    'Success should leave room for health, relationships, and peace.',
    'Do not win a life you do not enjoy living.',
    'Keep your standards high without making perfection the price of self-respect.',
    'You can want more without believing that what you have is worthless.',
    'Let purpose be stronger than pressure.',
    'When the path is uncertain, focus on the step directly in front of you.',
    'You do not need certainty to begin.',
    'Uncertainty is not proof that you are on the wrong path.',
    'Some answers become clear only after experience.',
    'Let yourself grow into the answer.',
    'A delayed decision is sometimes better than a rushed one.',
    'Take time to understand what you truly want.',
    'Do not make permanent choices from temporary emotions.',
    'Give difficult decisions enough quiet to become clear.',
    'You are allowed to change your mind when you learn something new.',
    'Changing direction is not always failure; sometimes it is wisdom.',
    'A new path can begin with one honest decision.',
    'You can carry lessons from the past without carrying its limitations.',
    'The future does not require you to repeat the past.',
    'Your next chapter does not have to resemble your last.',
    'Do not fear a blank page.',
    'A blank page is also an opportunity.',
    'You can build something meaningful from where you are.',
    'Begin with what you have and learn what you need along the way.',
    'Your life can change direction more than once.',
    'Protect your attention from things that leave you empty.',
    'Not every opinion deserves a place in your mind.',
    'You do not have to respond to everything.',
    'Silence can be wiser than winning an argument.',
    'Peace is sometimes choosing not to participate.',
    'Let some things pass without demanding an answer.',
    'You can disagree without becoming disrespectful.',
    'Do not spend your morning fighting battles that do not belong to you.',
    'Your peace is worth protecting.',
    'Choose carefully what you allow to occupy your thoughts.',
    'A calm mind can see possibilities that an angry mind misses.',
    'Take a breath before turning a moment into a reaction.',
    'Give yourself space between feeling and acting.',
    'You do not have to carry every conflict home with you.',
    'Release what you cannot change.',
    'Focus your effort where it can actually make a difference.',
    'Control what you can, accept what you cannot, and learn the difference.',
    'Sometimes peace begins with letting go of the need to be right.',
    'Do not let someone else\'s chaos become your identity.',
    'You can choose calm without choosing passivity.',
    'Remember that being alive means there is still something you can do.',
    'Another morning means another chance to make a better choice.',
    'You are not finished simply because yesterday was difficult.',
    'There is still time to become someone you respect.',
    'A new day does not erase the past; it gives you another chance to respond to it.',
    'Begin again as many times as necessary.',
    'Hope does not require certainty.',
    'Keep a little room in your heart for better days.',
    'Even slow healing is still healing.',
    'You do not have to rush your recovery.',
    'Some seasons are for building, others are for rebuilding.',
    'What hurts today may teach you how to care tomorrow.',
    'You can carry scars without letting them become your identity.',
    'Hard seasons can reveal strengths you did not know you had.',
    'Do not mistake a difficult season for the whole story.',
    'There can be light ahead even when you cannot see it yet.',
    'Keep walking until the view changes.',
    'You are allowed to hope again.',
    'The next chapter may surprise you.',
    'Stay long enough to see what your life can become.',
    'Ask yourself what kind of person you want to be today.',
    'Let your actions answer the question.',
    'Character is built in small moments when nobody is watching.',
    'Integrity means doing what is right when it is inconvenient.',
    'Be the same person when nobody is applauding.',
    'Keep promises you make to yourself.',
    'Your private choices shape your public character.',
    'Do not trade your values for temporary approval.',
    'It is better to lose approval than to lose yourself.',
    'Choose honesty even when a lie would be easier.',
    'Admit when you are wrong and learn from it.',
    'Apologize when you have caused harm.',
    'Take responsibility without turning responsibility into self-hatred.',
    'Own your mistakes, then use them to become wiser.',
    'Humility is not thinking less of yourself; it is seeing yourself honestly.',
    'Listen when someone points out something you cannot see.',
    'Being teachable is a strength.',
    'Let wisdom matter more than ego.',
    'You do not have to prove your worth every morning.',
    'Live in a way that makes your conscience peaceful.',
    'Do not wait for motivation to do what matters.',
    'Begin with five minutes if five minutes is what you have.',
    'The smallest useful action is better than another hour of planning.',
    'Action creates information that thinking alone cannot provide.',
    'Start small enough that you cannot talk yourself out of it.',
    'Make the next action obvious.',
    'Turn intention into something you can actually do.',
    'A goal becomes real when it becomes a habit.',
    'Build systems that help you keep promises to yourself.',
    'Consistency grows from returning after you fall off track.',
    'Missing one day does not require missing the next.',
    'Do not turn one mistake into a reason to quit.',
    'Reset and continue.',
    'Progress rarely happens in a straight line.',
    'Keep showing up.',
    'The work becomes easier when you stop negotiating with yourself every time.',
    'Discipline is remembering what matters when the mood changes.',
    'Make today\'s choice support tomorrow\'s choice.',
    'Let small wins build trust in yourself.',
    'You become reliable to yourself by keeping small promises.',
    'Your life is happening now, not after you achieve everything.',
    'Do not postpone living until the next milestone.',
    'Enjoy the journey without abandoning the destination.',
    'Make time for people who matter.',
    'Protect moments that cannot be repeated.',
    'A successful life needs memories, not only milestones.',
    'Do not let your phone become the first thing you give your attention to.',
    'Look up and notice the world around you.',
    'Talk to someone you care about while you still can.',
    'Make room for laughter.',
    'Make room for silence.',
    'Make room for curiosity.',
    'Keep learning things simply because they interest you.',
    'Let yourself be a beginner sometimes.',
    'Wonder is a form of attention.',
    'Life is larger than your current problem.',
    'There is more to you than what went wrong yesterday.',
    'Make today memorable for reasons that actually matter.',
    'Do not rush through a life you only get once.',
    'Be here for your own life.',
    'When someone hurts you, choose carefully what you carry forward.',
    'Pain can explain your reaction without excusing harmful behavior.',
    'You can protect yourself without becoming cruel.',
    'Do not let betrayal teach you to distrust everyone.',
    'One person\'s behavior does not define the whole world.',
    'Keep your heart open without abandoning your boundaries.',
    'Healing does not mean pretending nothing happened.',
    'You can forgive yourself for not knowing what you know now.',
    'Release the guilt that belongs to an older version of you.',
    'You are allowed to become wiser without becoming colder.',
    'Let difficult experiences deepen you, not harden you.',
    'Choose what lesson you want to keep.',
    'You cannot rewrite the event, but you can rewrite what it means to you.',
    'Do not give yesterday unlimited access to today.',
    'Your past deserves understanding, not permanent control.',
    'Make peace with what you cannot undo.',
    'Take the lesson and leave the unnecessary weight.',
    'You can remember without returning.',
    'You can care without carrying everything.',
    'You can move forward without forgetting where you came from.',
    'Be ambitious enough to grow and humble enough to learn.',
    'Be confident enough to try and humble enough to listen.',
    'Be strong enough to stand alone and wise enough to accept help.',
    'Be kind without becoming a doormat.',
    'Be disciplined without becoming cruel to yourself.',
    'Be patient without becoming passive.',
    'Be honest without using honesty as an excuse to hurt.',
    'Be brave without pretending you are never afraid.',
    'Be grateful without becoming complacent.',
    'Be hopeful without ignoring reality.',
    'Be responsible for your choices without blaming yourself for everything.',
    'Be willing to change when the evidence asks you to.',
    'Be curious before being certain.',
    'Be thoughtful before being reactive.',
    'Be present before being productive.',
    'Be intentional before being busy.',
    'Be generous when you can.',
    'Be gentle when someone is struggling.',
    'Be the person you needed when you were younger.',
    'Be someone your future self will thank.',
    'Today, choose one thing worth doing well.',
    'Today, speak to yourself with the same patience you give others.',
    'Today, do one thing your future self will appreciate.',
    'Today, make fewer promises and keep more of them.',
    'Today, listen more carefully.',
    'Today, complain less and act more where you have control.',
    'Today, notice something beautiful.',
    'Today, thank someone sincerely.',
    'Today, forgive yourself for being human.',
    'Today, learn something instead of proving something.',
    'Today, choose courage over avoidance.',
    'Today, choose progress over perfection.',
    'Today, choose purpose over distraction.',
    'Today, choose patience over reaction.',
    'Today, choose kindness when it costs you nothing.',
    'Today, choose integrity when nobody is watching.',
    'Today, choose to begin instead of waiting for the perfect moment.',
    'Today, remember that your attention shapes your experience.',
    'Today, make your actions match your values.',
    'Today, leave the world slightly better because you were in it.',
    'The morning is not asking you to solve your whole life.',
    'You only need to meet this day honestly.',
    'You can carry uncertainty and still carry hope.',
    'You can want change and still appreciate where you are.',
    'You can be unfinished and still be worthy.',
    'You can be learning and still be capable.',
    'You can be tired and still take one meaningful step.',
    'You can start again without permission.',
    'You can choose differently today.',
    'You can become more than your worst moment.',
    'You can outgrow old habits one choice at a time.',
    'You can change without becoming someone else.',
    'You can build confidence by keeping promises to yourself.',
    'You can create momentum from one small action.',
    'You can make a difference without being famous.',
    'You can help someone without fixing their whole life.',
    'You can be a source of calm in a difficult moment.',
    'You can make today\'s ordinary moments meaningful.',
    'You can live with purpose without having every answer.',
    'You can begin now.',
    'Your morning does not need to be perfect to be meaningful.',
    'Give yourself a reason to respect the way you spend today.',
    'The person you become is built in moments nobody applauds.',
    'Choose habits that make your life easier to respect.',
    'Do not let a temporary setback become a permanent belief.',
    'A better life is often built through better ordinary days.',
    'Your attention is a direction; choose where you point it.',
    'The things you repeatedly notice become the story you tell yourself.',
    'Make your inner voice a place where you can safely return.',
    'Speak to yourself as someone you are responsible for caring for.',
    'You can demand more from yourself without despising yourself.',
    'Growth needs honesty more than it needs perfection.',
    'A peaceful mind is not a mind without problems.',
    'Peace is learning which problems deserve your attention.',
    'You do not need to answer every question today.',
    'Sometimes the wisest move is to pause.',
    'A pause can prevent a reaction you will later regret.',
    'Think before you react, especially when you feel certain.',
    'Strong people can change their minds when they learn.',
    'Wisdom includes knowing when you do not know.',
    'Ask better questions before searching for faster answers.',
    'The quality of your choices depends on the quality of your attention.',
    'Do not let urgency turn every problem into an emergency.',
    'Some things improve simply because you give them time.',
    'Patience is not doing nothing; it is refusing to rush badly.',
    'Let today\'s effort be enough for today\'s responsibility.',
    'You can care deeply without carrying everything.',
    'Your best effort may look different on different days.',
    'Consistency does not mean being perfect every day.',
    'Consistency means returning after imperfect days.',
    'The ability to restart is one of your greatest strengths.',
    'A setback is not a command to stop.',
    'If you fall behind, begin from where you are.',
    'Do not punish tomorrow for what happened yesterday.',
    'A new choice can begin a new pattern.',
    'Change becomes real when behavior follows intention.',
    'Wanting something is different from making room for it.',
    'If it matters, give it time and attention.',
    'Protect the habits that protect your future.',
    'Do not make your future compete with your distractions.',
    'Your phone can wait; your life is happening now.',
    'The world will always offer another distraction.',
    'You decide what gets the first part of your day.',
    'Start with what gives your day direction.',
    'A meaningful morning begins with a meaningful intention.',
    'Before asking what you can get today, ask what you can give.',
    'Give your best energy to what matters most.',
    'Do not spend your strongest hours on things you do not value.',
    'Use your time as if it carries meaning, because it does.',
    'Time is something you spend whether you notice or not.',
    'Spend time in ways your future memories will appreciate.',
    'Some of the best investments cannot be measured in money.',
    'Invest in your health, your character, and your relationships.',
    'Take care of your body without making it your whole identity.',
    'Take care of your mind without believing every thought it produces.',
    'Take care of your relationships before distance becomes permanent.',
    'Call someone you love before you have a reason to.',
    'Tell people you appreciate them while they can hear it.',
    'Do not assume people know what they mean to you.',
    'Kindness becomes more valuable when it is specific.',
    'Thank people for the things you might normally overlook.',
    'A sincere thank you can make an ordinary day memorable.',
    'Give credit without needing recognition in return.',
    'Celebrate someone else\'s progress without comparing it to yours.',
    'Another person\'s success does not reduce your possibility.',
    'You can admire someone without becoming smaller beside them.',
    'Comparison often hides the progress you have already made.',
    'Look back sometimes, not to live there, but to see how far you came.',
    'Remember the person who once wished for the opportunities you have now.',
    'Use your opportunities with humility.',
    'Privilege carries responsibility toward others.',
  ]